test:
  override:
    - "true"
    
deployment:
  production:
    branch: master
    commands:
      - git remote add production dokku@dokku.jasonbehnke.net:personal-site
      - git push production master -f

